### ISSUE TITLE
Take command line arguments

### ISSUE THREAD

**Issue by 48ca** [jamesthoughton/ttyvideo#1]
Examples include --no-exit (useful for images), --loop, --no-audio (if audio is implemented), --help, --fps <arg, frequency>, -w (--width) <arg, pixels>, -h (--height) <arg, pixels>, --sleep <arg, seconds>, --pause <arg, milliseconds>

**Comment by 48ca** [comment]
also take --disallow-interrupts to prevent the use of ^C to stop execution

**Comment by 48ca** [comment]
Implement option overlap: allow preference, but also allow fatal errors when option preference shouldn't be used.
Example: --no-exit and --loop should throw an error because they cause two different, non-default behaviors for videos (--no-exit stops at final frame, --loop restarts when it gets to the last frame).
However, --sleep 1 and --no-exit should give a warning (however --loop should not, as paired, sleep should pause the restart) but it should still run, --no-exit taking preference (stopping indefinitely at the last frame).

**Comment by czhao39** [comment]
Also add --string for maximum memes

**Comment by 48ca** [comment]
and --suppress-errors http://stackoverflow.com/questions/584868/rerouting-stdin-and-stdout-from-c
